### ISSUE TITLE
README example - Unbound value not_found

### ISSUE THREAD

**Issue by pjhampton** [rgrinberg/opium#141]
Hey 👋 

It seems that the example on the readme is raising the following error:

```
dune build
File "hello_world.ml", line 14, characters 2-11:
14 |   not_found (fun req ->
       ^^^^^^^^^
Error: Unbound value not_found
```

I'm using OCaml version 4.09.0 and Opium 

```
opium                              0.17.1       Sinatra like web toolkit based on Lwt + Cohttp
```

Is this an outdated doc or is there an issue on my end?

**Comment by anuragsoni** [comment]
I should clarify this in the readme. not_found is not present in the current released version on opam. I will prepare a new release soon but in the meantime you can pin it to the dev version from master.

**Comment by anuragsoni** [comment]
I've made a pull request for a new release https://github.com/ocaml/opam-repository/pull/16073

**Comment by anuragsoni** [comment]
The new release is now available on opam
