### ISSUE TITLE
Is version 1.0 on the horizon?

### ISSUE THREAD

**Issue by rbjorklin** [rgrinberg/opium#142]
I know it's just a number but to many (myself included) it signals maturity. This has been taken up in the past on the OCaml forums: https://discuss.ocaml.org/t/the-forever-beta-issue/1779

Feel free to close this issue, I just wanted to bring this up.

**Comment by anuragsoni** [comment]
Thank you for raising this point. There are a couple of things that I’d like to happen before a 1.0 release. Support for web sockets (supporting thing will lead to some breaking changes), adding more tests/documentation. I’m closing this for now, but I’m definitely very interested in getting this to 1.0 in a reasonable time frame. Things get a little slow at times as I work on this whenever I can find bandwidth outside of the paying job, thank you for being patient. 

Best,
Anurag
