### ISSUE TITLE
Error: Version 1.11 of dune is not supported.

### ISSUE THREAD

**Issue by decapo01** [rgrinberg/opium#143]
When attempting to run the example as in the README I get this error

```
File "dune-project", line 1, characters 11-15:
1 | (lang dune 1.11)
               ^^^^
Error: Version 1.11 of dune is not supported.
Supported versions:
- 0.0
- 1.0 to 1.2
```

**Comment by anuragsoni** [comment]
The error indicates that you'd need to install dune 1.11 or above. How are you installing ocaml/dune?
If using opam you can ensure you get the newer versions by running:
```ocaml
opam update
```
