### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by decapo01** [rgrinberg/opium#144]
I've come back to try this library a few times and I've never got it to work.  The last time was about 1.5 to 2 years ago.  At that time I was familiar with Scala and looking to branch out and I have since become more familiar with Haskell and have got projects up and running in it.

Could one of the core authors create a basic tutorial of a simple crud rest api that starts from nothing to finish?  Installing with opam, creating a a project directory, writing the source file, building with dune then running.  Maybe even providing a connection to a Postgresql database.  Just a simple semi real world tutorial for those of us coming from other functional languages so we can get started with this.

**Comment by roddyyaga** [comment]
See [this](https://shonfeder.gitlab.io/ocaml_webapp/) tutorial (linked in readme).

**Comment by anuragsoni** [comment]
The tutorial referenced by @roddyyaga is nicely written detailed introduction to how to setup an application starting from the opam, ocaml compiler, build tools etc. It covers the topics that you are looking from (it includes details about how to connect to and use postgresql using ocaml)
