### ISSUE TITLE
conduit-lwt-unix no longer calls Mirage_crypto_rng_unix.initialize

### ISSUE THREAD

**Issue by xguerin** [rgrinberg/opium#171]
This change happened in version `2.2.2`. Users updating to that version and using `opium` will be greeted with the following error:

```
[WARNING] Uncaught exception in handler: The default generator is not yet initialized.
To initialize the RNG with a default generator, and set up entropy collection and periodic reseeding as a background task, do the following:
  If you are using MirageOS, use the random device in config.ml: `let main = Mirage.foreign "Unikernel.Main" (random @-> job)`, and `let () = register "my_unikernel" [main $ default_random]`.
  If you are using Lwt, execute `Mirage_crypto_rng_lwt.initialize ()` at the beginning of your event loop (`Lwt_main.run`) execution.
  If you're using neither MirageOS nor lwt, there is no periodic reseeding. For an initial seed from getrandom(), execute `Mirage_crypto_rng_unix.initialize ()`. You can use `Mirage_crypto_rng.accumulate` and `Mirage_crypto_rng.reseed` to
 reseed the RNG manually.
```

I am not sure anything can be done in `opium` but I'm hoping cross-referencing 
https://github.com/mirage/ocaml-conduit/issues/318 might help anyone running into the issue.

**Comment by avsm** [comment]
Sorry about this, it slipped past me. For the moment, conflicting opium with conduit-lwt-unix.2.2.2 would be best.

**Comment by anuragsoni** [comment]
> Sorry about this, it slipped past me. For the moment, conflicting opium with conduit-lwt-unix.2.2.2 would be best.

Is this just adding a constraint of `< 2.2.2`? I can make a pull request to the opam-repository later today.

**Comment by anuragsoni** [comment]
Now that conduit-lwt-unix 2.2.2 is disabled in opam repo https://github.com/ocaml/opam-repository/pull/16648 I think there is no change required in opium just yet

**Comment by anuragsoni** [comment]
Looks like this was resolved and we don't need to do anything special in opium. [1]
I'm closing this issue for now.

[1] https://github.com/mirage/ocaml-conduit/issues/318#issuecomment-646985073
