### ISSUE TITLE
Examples Package

### ISSUE THREAD

**Issue by rgrinberg** [rgrinberg/opium#196]
As far as I can see, there's no package that's making sure the examples are built.

**Comment by anuragsoni** [comment]
Its not a package, but we do have an alias that builds all the examples

https://github.com/rgrinberg/opium/blob/0fe299bddd816406457370c63034bf80d7926043/examples/dune#L13

This is run on the CI with every build.

**Comment by rgrinberg** [comment]
I see. As far as I can tell, we don't specify the external dependencies of examples though.

**Comment by anuragsoni** [comment]
@rgrinberg At the moment its done manually via 
https://github.com/rgrinberg/opium/blob/master/.github/workflows/ci.yml#L44-L46

This can definitely be improved. For my clarification were you thinking of creating a opam file for the examples? That'd indeed make it easy to drive the installation of dependencies on CI, but it might make releases awkward. I'm not sure if dune-release allows ignoring certain packages in the worktree.

**Comment by tmattio** [comment]
I removed the additional dependencies in the examples, so I think we can close this.
