### ISSUE TITLE
Be json implementation agnostic (Yojson vs. Jsonm)

### ISSUE THREAD

**Issue by rgrinberg** [rgrinberg/opium#21]
Both are popular and the user should be allowed to use either one.

**Comment by rgrinberg** [comment]
Decided against this. Nobody seems to mind.

**Comment by XVilka** [comment]
Would be nice to have though. E.g. in the rest of the code I use Yojson for forming JSON output, requires converting to String. And Yojson is almost 2 times faster according to your blog.

**Comment by rgrinberg** [comment]
You can still use yojson, you just need a little more boilerplate to do it.
