### ISSUE TITLE
Opam produces a warning about rock being an unknown package when installing via pin

### ISSUE THREAD

**Issue by rosalogia** [rgrinberg/opium#224]
The README currently suggests that the version of opium on the master branch of the repository can be obtained via opam using the following commands
```
$ opam pin add rock --dev-repo
$ opam pin add opium --dev-repo
```
However, this seems to produce a warning as opam is unable to find rock as a dependency. Why might this be?
![image](https://user-images.githubusercontent.com/66163965/100428298-bfa2a380-3061-11eb-8111-83ca8d1890ac.png)

**Comment by tmattio** [comment]
Hi @rosalogia!

`rock` is not published on Opam yet, so you have to give Opam the repo's URL:
```
opam pin add rock.~dev https://github.com/rgrinberg/opium.git
opam pin add opium.~dev https://github.com/rgrinberg/opium.git
```

**Comment by rosalogia** [comment]
Thanks! Should this be updated in the README?

**Comment by tmattio** [comment]
Yes - I'll update the instructions to install the master version 👍
