### ISSUE TITLE
Request and Response module functions used in examples appear to be unbound

### ISSUE THREAD

**Issue by rosalogia** [rgrinberg/opium#225]
While trying to experiment with two of the examples in the example directory, particularly [file_upload](https://github.com/rgrinberg/opium/tree/8983b465869647b7815be4660f434592abc395f5/example/file_upload) and [json_request](https://github.com/rgrinberg/opium/tree/8983b465869647b7815be4660f434592abc395f5/example/json_request), I've run into issues where functions that are used in those examples and are clearly part of opium are unbound on my end. For example, this is taken from the json_request example in which only Opium is open:
![image](https://user-images.githubusercontent.com/66163965/100429164-ef9e7680-3062-11eb-9768-13dab5bec64f.png)
What might be causing this issue? Similar issues arise with the file_upload example. It seems like the only functions I can access are the ones you can read about in the [documentation](https://rgrinberg.github.io/opium/opium/Opium/index.html), which don't include many of the functions used in examples.

**Comment by tmattio** [comment]
Looking at your other issue #224, you're probably not using the master version of Opium. Let's solve your issue there 🙂
