### ISSUE TITLE
conf-libev dependency

### ISSUE THREAD

**Issue by lindig** [rgrinberg/opium#261]
Opium lists `conf-libev` as a dependency but is it really required? I can't seem to find any reference to the library in the code.

This only turned up when I tried to install opium on an ARM-based Mac (M1) where `conf-libev` does not find the library - see https://github.com/ocaml/opam-repository/issues/18167. There is also an open PR that asks to remove the dependency: https://github.com/rgrinberg/opium/pull/254

**Comment by aantron** [comment]
I assume it's to help uesrs not install Lwt without libev, causing people to easily hit the `select` fd limit.
