### ISSUE TITLE
Getting the client (IP) address

### ISSUE THREAD

**Issue by aantron** [rgrinberg/opium#264]
Is this possible with Opium?

From this line, which appears to ignore the client address

https://github.com/rgrinberg/opium/blob/4e71f0bbecacd974342b4814f8459202c730e45f/opium/src/app.ml#L23

...my guess is that it is not possible at the moment.

**Comment by anuragsoni** [comment]
Hmm, this was most likely an oversight when initially switching to httpaf. We shouldn't ignore the client address.
