### ISSUE TITLE
Program ocaml-crunch not found

### ISSUE THREAD

**Issue by whoek** [rgrinberg/opium#266]
Hello -- 

Trying to get opium going I am getting the following error.

```
$ dune build
File "opium-graphql/src/dune", line 6, characters 9-26:
6 |   (run %{bin:ocaml-crunch} -m plain ../asset -o asset.ml)))
             ^^^^^^^^^^^^^^^^^
Error: Program ocaml-crunch not found in the tree or in PATH
 (context: default)


$ opam switch
#  switch                          compiler                        description
→  4.10.0+mingw64c                 ocaml-variants.4.10.0+mingw64c  4.10.0+mingw64c

```
Some background:
- I was able to get lwt examples in the inhabitedtype/httpaf repository going fine.
- I am using Ocaml on Windows 10
Any guidance would be appreciated.

Thanks for posting opium.

(**_Edit:_** all examples provided compiles OK except graphql )

**Comment by tmattio** [comment]
Hi @whoek!

You'll need to install `crunch` manually to compile that example:

```
opam install crunch
```

**Comment by whoek** [comment]
Many Thanks
