### ISSUE TITLE
`splat` returns unescaped strings

### ISSUE THREAD

**Issue by m2ym** [rgrinberg/opium#30]
```OCaml
let foo =
  get "/*" begin fun req ->
    Lwt_io.eprintl (String.concat "/" (splat req)) >>= fun _ -> ...
  end
```

outputs not `#a/b` but `%23a/b` for a request `/%23a/b`. Is this as you expected?

**Comment by m2ym** [comment]
Should we use `**` for this purpose? I got an error like `(Invalid_argument "** is only allowed at the end")` when using `/**` instead of `/*`

I don't make sense the following code.

https://github.com/rgrinberg/opium/blob/8323e729053af022cf14a493d12b12fcbb207f03/opium/simple_route.ml#L31

**Comment by rgrinberg** [comment]
* First instance is indeed a bug

* The purpose of `**` is matching past a slash in a path. E.g. `/x/**` will match `/x/123/456`, `/x/123`, `x/yyyzzz` etc.

**Comment by rgrinberg** [comment]
@m2ym I've fixed the issue in master. Feel free to ask more questions though.

**Comment by m2ym** [comment]
@rgrinberg Great. Thanks.
