### ISSUE TITLE
Is this the best practice to extract the get parameter?

### ISSUE THREAD

**Issue by ghost** [rgrinberg/opium#32]
I've read the code in the examples folder, I found all the example put its parameter in the absolute path.

I want to extract the get parameter such as `http://localhost:9001/gid?ua=haha`, and I found a way

``` ocaml
let getid = get "/gid" (fun req ->
  let uri = Request.uri req in
  let ua = Uri.get_query_param uri "ua" in
  match ua with
  | Some cont -> begin `String cont |> respond' end
  | None -> begin `String "none" |> respond' end)
```

Well, it works as I expected, but I'm wondering if it's the best practice, because if there are many get arguments, the pattern matching code would be not elegant.

**Comment by rgrinberg** [comment]
I agree the situation currently isn't perfect and I have a couple of ideas on how to improve it. However, Uri  itself could also be improved for extracting multiple arguments.

For example, we can imagine a couple of functions:

``` ocaml
(* only match if all query params are present *)
val get_all_qp : Uri.t -> string list -> (string list) option
(* allow for partial matches of parameters list *)
val get_all_qp' : Uri.t -> string list -> (string option) list
```

You can then only have a single pattern match for the common case:

``` ocaml
match get_all_qp uri ["ua"; "xx"; "yyy"] with
| Some [ua; xx; yyy] -> ...
| _ -> ...
```

The above functions could be implemented on top of `Uri.query`.

@dsheets do you think a helper like that could be useful?

**Comment by dsheets** [comment]
That does sound useful and should probably be included in `uri`. If you spec it in an issue, we can make sure it gets in the next release (hopefully this spring).

Something like

```ocaml
let get_all_qp' uri = List.map (Uri.get_query_param uri)
```
?

and

```ocaml
let get_all_qp uri keys = List.fold_right (fun key -> function
  | None -> None
  | Some l -> match Uri.get_query_param uri key with None -> None | Some v -> Some (v :: l)
) keys (Some [])
```
?

@liweijian might also find `Uri.query` useful.

**Comment by tmattio** [comment]
#179 added functions to get query parameters from a request, namely `Request. query_list ` and `Request.query`. 

You can either use `query` if you're interested in only one parameter, or `query_list` if you want to check all of the parameters.

I think it answers the initial question, so I'm going to close this, but don't hesitate to reopen if you have any more questions.
