### ISSUE TITLE
How to properly shut down an opium application?

### ISSUE THREAD

**Issue by antoine1fr** [rgrinberg/opium#34]
My opium application needs to do some work before shutting down, so I can't just kill it. Unfortunately the Exit exception is caught by opium's main loop.

Is there a proper way to exit an app?

**Comment by antoine1fr** [comment]
> Is there a proper way to exit an app?

EDIT : Is there a proper way to exit the main loop?

**Comment by rgrinberg** [comment]
How are you running the opium app? There are 2 options here:

1. the built in command line runner 

2. Manually using https://github.com/rgrinberg/opium/blob/ba996899cf8bc1eedfa7225806aa5be7cf9bcc5f/opium/app.mli#L55

**Comment by rgrinberg** [comment]
In the case of 1. I don't think it's currently possible but I will fix it (this might cause minor breakage though). In the case of 2. it's simple enough to just do something like `app |> App.start |> Lwt.cancel` to shutdown the app and have `at_exit` or whatever called.

**Comment by antoine1fr** [comment]
Thanks for your reply!

I'm currently using the command line runner. I totally missed the App.start function. ^^

I'll switch to the manual approach for now and use your suggestion.

**Comment by rgrinberg** [comment]
@antoine1fr glad that works for you. Do you find the command line runner useful however? I could fix it to also allow this but it will require some modification of user code.

**Comment by antoine1fr** [comment]
@rgrinberg The command line runner is really useful when I don't want to fine tune the command line interface, which was always the case as of today.

A fix would be awesome. I don't mind rewriting a bit of my code.

Thanks for your time.

**Comment by rgrinberg** [comment]
@antoine1fr I've pushed out a fix. Checkout https://github.com/rgrinberg/opium/blob/60e57ca75d732056c7060fb3ffd7cb68ac71b087/examples/exit_hook_example.ml#L14 for an example.

Let me know if there's any other issues.

**Comment by rgrinberg** [comment]
@antoine1fr I'm closing this as I think I've fixed. Feel free to re-open if you have concerns.
