### ISSUE TITLE
Using ~f for request handler might be better syntactically

### ISSUE THREAD

**Issue by keleshev** [rgrinberg/opium#35]
This is a nitpick, but in case you have not thought about it, you can get rid of begin-end block here if you use a labelled parameter:

```ocaml
let h =
  put "/hello/:x/from/:y" begin fun req ->
    (* ... *)
  end
```

With labelled parameter (could be `~f` or `~action`):

```ocaml
let h =
  put "/hello/:x/from/:y" ~f:fun req ->
    (* ... *)
```

This is a quirk of OCaml syntax that I discovered recently.

**Comment by rgrinberg** [comment]
You can also get rid of the block with `put "/hello/:x/from/:y" @@ fun req ->`. I don't think it's worth breaking everything for this though.

**Comment by keleshev** [comment]
Haven't thought about `@@`, nice.
