### ISSUE TITLE
core_kernel dependency?

### ISSUE THREAD

**Issue by samoht** [rgrinberg/opium#40]
Just wondering if the dependency towards core_kernel is really necessary? Seems that you only need an universal map implementation.

**Comment by rgrinberg** [comment]
I agree. However this has been a low priority for me until someone is actually affected by this since it's kind of a large and boring change.

I'm not aware of any standalone universal map implementations so I've also been kind of waiting for one to pop up on opam. I'm happy turn the gears on this if someone needs this however.

**Comment by samoht** [comment]
That's not urgent at all, but I am starting to use it [in some of my new projects](https://github.com/samoht/ciso) (and I consider to maybe using it in Irmin in a so-no-distant future). There are few implementation or universal map in the various libraries from Daniel, but there is no stand-alone one at the moment.

**Comment by hcarty** [comment]
opium without Core_kernel required and a stand-alone universal map implementation both sound like wonderful things to have.

**Comment by rgrinberg** [comment]
I think @dbuenzli has some univ map implementations lying around.

Any chance we'll see them released?

**Comment by rgrinberg** [comment]
I think @dbuenzli has some univ map implementations lying around.

Any chance we'll see them released?

**Comment by dbuenzli** [comment]
> Any chance we'll see them released?

Yeah sure, here's a release: 

```ocaml
(** Dictionaries.

    A dictionary is a set of {{!keys}keys} mapping to typed values. *)
module Dict : sig

  (** {1:keys Keys} *)

  type 'a key
  (** The type for dictionary keys whose lookup value is ['a]. *)

  val key : unit -> 'a key
  (** [key ()] is a new dictionary key. *)

  (** {1:dict Dictionaries} *)

  type t
  (** The type for dictionaries. *)

  val empty : t
  (** [empty] is the empty dictionary. *)

  val is_empty : t -> bool
  (** [is_empty d] is [true] iff [d] is empty. *)

  val mem : 'a key -> t -> bool
  (** [mem k d] is [true] iff [k] has a mapping in [d]. *)

  val add : 'a key -> 'a -> t -> t
  (** [add k v d] is [d] with [k] mapping to [v]. *)

  val rem : 'a key -> t -> t
  (** [rem k d] is [d] with [k] unbound. *)

  val find : 'a key -> t -> 'a option
  (** [find d k] is [k]'s mapping in [d], if any. *)

  val get : 'a key -> t -> 'a
  (** [get k d] is [k]'s mapping in [d].

      {b Raises.} [Invalid_argument] if [k] is not bound in [d]. *)
end = struct

  (* Dictionaries see http://mlton.org/PropertyList *)

  (* Keys *)

  module Key = struct
    let univ (type s) () =
      let module M = struct exception E of s option end in
      (fun x -> M.E (Some x)), (function M.E x -> x | _ -> None)

    let key_id =
      let count = ref (-1) in
      fun () -> incr count; !count

    type 'a key =
      { id : int;
        name : string;
        to_univ : 'a -> exn;
        of_univ : exn -> 'a option; }

    let create () (type v) =
      let id = key_id () in
      let to_univ, of_univ = univ () in
      { id; name = ""; to_univ; of_univ }

    type t = V : 'a key -> t
    let compare (V k0) (V k1) = (compare : int -> int -> int) k0.id k1.id
  end

  type 'a key = 'a Key.key
  let key = Key.create

  (* Dictionaries *)

  module M = (Map.Make (Key) : Map.S with type key = Key.t)
  type t = exn M.t

  let empty = M.empty
  let is_empty = M.is_empty
  let mem k d = M.mem (Key.V k) d
  let add k v d  = M.add (Key.V k) (k.Key.to_univ v) d
  let rem k d = M.remove (Key.V k) d
  let find k d = try k.Key.of_univ (M.find (Key.V k) d) with Not_found -> None
  let get k d = match find k d with
  | Some v -> v
  | None -> invalid_arg "key unbound in dictionary"

  let pp ppf d = Format.fprintf ppf "@[(dict TODO)@]"
end

```

**Comment by dbuenzli** [comment]
Most of the time you want to associate [more information](https://github.com/samoht/assemblage/blob/master/lib/as_conf.ml#L56-L66) to keys so I think there's little use in having a generic univ map.

**Comment by dbuenzli** [comment]
Well that said it could be functorized. But I don't have the time for that at the moment.

**Comment by c-cube** [comment]
If people here are still interested, I can take @dbuenzli 's implementation, functorize it and put it on opam (as `umap` or something like this). Then I could try and remove `core_kernel` from opium (which seems like it's not too big anyway).

**Comment by hcarty** [comment]
@c-cube I'm still interested, and happy to test the results.

**Comment by rgrinberg** [comment]
@c-cube i'd definitely be interested ever since I learned that core_kernel isn't as portable as I thought.

**Comment by dbuenzli** [comment]
Since I have been c&p and slightly modifying this in many of my projects. I'd like to do this myself if @c-cube doesn't object.

**Comment by c-cube** [comment]
Please do; you can start from `opium_map` from #47 if you wish, it's functorized already.

**Comment by c-cube** [comment]
Please do; you can start from `opium_map` from #47 if you wish, it's functorized already.

**Comment by dbuenzli** [comment]
Ok so here something: http://erratique.ch/software/hmap/doc/Hmap.html

The `u` was somewhat an implementation detail so it's called `hmap` (this implementation doesn't use universal types but type identifiers). This can be tried with:
```
 opam pin add hmap http:/erratique.ch/repos/hmap.git
```
Feedback welcome.

**Comment by c-cube** [comment]
Just a remark: using an open type means that `hmap` (and therefore opium) would only work on versions of OCaml more recent than 4.02, doesn't it?
Otherwise the API seems really nice.

**Comment by rgrinberg** [comment]
I don't mind the 4.02 restrictions because I'd like to chuck out camlp4 as soon as cohttp switches.

**Comment by dbuenzli** [comment]
> OCaml more recent than 4.02, doesn't it?

Yes. I thought that now that 4.03 is around the corner... If people are too annoyed I'll gadly reimplement it over universal types (it's not hard, see e.g. https://github.com/dbuenzli/logs/commit/8f9ee6b87a2919149e8011bf4467b2423be2defa). But I think the type identifier version should be much more efficient (e.g. on lookup), though I didn't measure it.

**Comment by rgrinberg** [comment]
This will be in the next release.
