### ISSUE TITLE
about the name (aka: bikeshedding)

### ISSUE THREAD

**Issue by justgage** [rgrinberg/opium#44]
First off I just want to thank you so much for this wonderful product that you all have been creating. It makes me so happy to see a viable way to make web apps in OCaml. Keep up the good work.

This is totally bikesheading on my part but I find it odd to name this project after a drug. Is there a reason for this? I feel like a drug theme is not exactly the most professional. Naturally the name of somthing isn't the most important thing but I feel it will matter in the marketing aspect. Just my two cents.

**Comment by rgrinberg** [comment]
I understand your concern. I do have some counterpoints in favor of keeping the name though:

1) Avoid annoying breakage and confuse people that already know about opium.

2) Opium is a relatively unique name in the context of programming

3) There's plenty of names like that out there, [flask](http://flask.pocoo.org/), [cocaine](https://github.com/thoughtbot/cocaine) and it doesn't seem to have impacted adoption.

That being said, if enough people really hate the name I will change it so I will leave this ticket open.
