### ISSUE TITLE
DSL for routes

### ISSUE THREAD

**Issue by justgage** [rgrinberg/opium#46]
I was looking at Opium as it's currently works and wondering if some sort of DSL for routes would be useful. It would basically provide a small layer of syntactic sugar that would boil down to exactly what it is now, just allowing to define routes in line easier. My main modivation is to try to get it closer to Sinatra's DSL.

rough example:

```ocaml
let middleware = def_middleware [ auth, capitalizer ]

let routes = def_routes [
   GET "hello/:name" print_name,
   POST "hello/:name post_name
]

let () =
    App.simple
    ~middleware
    ~routes
```

I apologize in advance if there exists something in the code base that's already like this. I'm not very familiar with it yet.

**Comment by justgage** [comment]
Some other possible inspiration: https://github.com/elixir-lang/plug#the-plug-router. Obviously OCaml doesn't have macros like Elixir does however I think we might be able to make something similar with types.

**Comment by rgrinberg** [comment]
Sorry for the late reply. I'm not sure how much better your way of defining routes is better than Opium's but it certainly seems possible to implement. Just change the `GET/POST` to polymorphic variants and defining `def_routes` should be a very short function. Same for middleware, just remember that `,` is for tuples and not lists.

**Comment by justgage** [comment]
Yeah I'm not convinced yet either... In fact thinking about it I think it might provide a layer of abstraction that would provide little value and cloud what's going on underneath the hood. Ah yes, that's an embarrassing mistake, you can tell that I've been writing in other languages as of late.
