### ISSUE TITLE
before 0.15

### ISSUE THREAD

**Issue by c-cube** [rgrinberg/opium#52]
~~build is broken for me (because of `fieldslib.syntax`), and I think it would be nice to get rid of camlp4 (is there a ppx replacement for fieldslib?).~~

Also, hosting doc on github pages should be easy, I can submit a PR if you want (once I find how to generate the doc!)

**Comment by rgrinberg** [comment]
That would be very welcome. Gerd documented how to do this with omake in http://www.camlcity.org/knowledge/kb_001_omake_recipes.html#ocamldoc

I figured it won't be worth the effort until docock is released but I should probably stop holding my breath.

**Comment by c-cube** [comment]
Oh, generating the doc can be done afterward, anyway, don't let it block the release ;-)

**Comment by anuragsoni** [comment]
@c-cube I've pushed odoc output to github pages: https://rgrinberg.github.io/opium/

Any suggestions about what content you'd like to see in the docs is very welcome.
