### ISSUE TITLE
Mirage compatibility?

### ISSUE THREAD

**Issue by sgrove** [rgrinberg/opium#58]
I haven't tried to use Opium with my Mirage site for some time now, but I'm curious if it would work? I'd like to drop my current janky routing.

**Comment by chrismamo1** [comment]
As far as I know Opium uses Cohttp, which was made by the MirageOS team. The `unix` dependencies, however, may be problematic.

**Comment by anuragsoni** [comment]
Opium_kernel is usable under mirage. You'd need to setup some plumbing to configure the application to replicate what's done via the Opium.App module, but the kernel should work on mirage. Let me know if you are still interested in this and i can help if needed.

Note that the current master branch is now based on httpaf and you can see an example of running that under mirage at https://github.com/anuragsoni/ocaml-opium-unikernel

Its using https://github.com/dinosaure/paf-le-chien for the httpaf implementation
