### ISSUE TITLE
Installation error on Arch Linux

### ISSUE THREAD

**Issue by orbifx** [rgrinberg/opium#63]
Opium isn't installing because `libfam.so.0` is missing. Should that be in `depext`?

```
The following actions will be performed:
  ∗  install opium 0.15.0

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[opium] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of opium failed at "make install".
Processing  1/1: [opium: ocamlfind remove]
#=== ERROR while installing opium.0.15.0 ======================================#
# opam-version 1.2.2
# os           linux
# command      make install
# path         .opam/4.03.0/build/opium.0.15.0
# compiler     4.03.0
# exit-code    2
# env-file     .opam/4.03.0/build/opium.0.15.0/opium-27414-d2c37b.env
# stdout-file  .opam/4.03.0/build/opium.0.15.0/opium-27414-d2c37b.out
# stderr-file  .opam/4.03.0/build/opium.0.15.0/opium-27414-d2c37b.err
### stderr ###
# omake: error while loading shared libraries: libfam.so.0: cannot open shared object file: No such file or directory
# make: *** [Makefile:21: install] Error 127
```

**Comment by rgrinberg** [comment]
This is probably a depext of one of Opium's dependencies. Opium doesn't use any non OCaml libs directly. Which archlinux provides libfam?

**Comment by orbifx** [comment]
It's called Gamin. It's for file monitoring.

I checked omake depext and it wasn't it either. According to it's output anyway.

**Comment by rgrinberg** [comment]
Hmm, I have no idea who might require this library. It's definitely one of Opium's dependencies. I'm thinking it's omake itself perhaps?

**Comment by orbifx** [comment]
As I mentioned in the last message, I checked `omake` as it was it my first suspect too. But `depext` didn't return anything, unless they haven't listed it.

**Comment by rgrinberg** [comment]
Why I suspect omake as well:

I know omake uses libfam to for its "polling mode" (activated with -P).  But I'm also aware that it's disabled by default since its pretty broken. One thing you could check is trying to build opium manually with `$ omake -v` and see what that gives you. And yes, I'm not surprised why it isn't listed.

But again, this is all speculation at this point.

**Comment by orbifx** [comment]
```
⇒  ldd .opam/4.03.0/bin/omake 
        linux-vdso.so.1 (0x00007fff63f68000)
        libfam.so.0 => /usr/lib/libfam.so.0 (0x00007f5b35f38000)      # /!\ here
        libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007f5b35ccb000)
        libreadline.so.6 => /usr/lib/libreadline.so.6 (0x00007f5b35a81000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f5b3577d000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f5b35579000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f5b351db000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5b3613f000)
```

I can't find `omake`'s issue tracker; website link seems to be outdated. Do you know what it is?

**Comment by orbifx** [comment]
This should do: https://github.com/ocaml/opam-repository/issues/7646

**Comment by rgrinberg** [comment]
This  is the issue tracker: https://github.com/ocaml-omake/omake/issues

Please note however, that the official omake repo above still hasn't made a release to opam yet. Which means that it might include a fix to this issue anyway.

From my understanding however, all the libfam support in omake is completely broken.
