### ISSUE TITLE
Installation error on OSX

### ISSUE THREAD

**Issue by bladewang** [rgrinberg/opium#64]
Opium isn't installing, but I don't know how to resolve ...

    =-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
    [opium] https://github.com/rgrinberg/opium.git already up-to-date

    =-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
    [ERROR] The compilation of opium failed at "make install".
    Processing  1/1: [opium: ocamlfind remove]
    #=== ERROR while installing opium.0.15.0 ======================================#
    # opam-version 1.2.2
    # os           darwin
    # command      make install
    # path         .opam/system/build/opium.0.15.0
    # compiler     system (4.03.0)
    # exit-code    2
    # env-file     .opam/system/build/opium.0.15.0/opium-79612-d8a4ae.env
    # stdout-file  .opam/system/build/opium.0.15.0/opium-79612-d8a4ae.out
    # stderr-file  .opam/system/build/opium.0.15.0/opium-79612-d8a4ae.err
    ### stdout ###
    # [...]
    # --- Checking for ocamllex.opt... (found /usr/local/bin/ocamllex.opt)
    # --- Checking whether ocamlc understands the "z" warnings... (yes)
    # *** omake: finished reading OMakefiles (0.03 sec)
    # --- Checking if ocamldep understands -modules... (yes)
    # - build opium_kernel opium_hmap.cmi
    # + ocamlfind ocamlc.opt -package hmap,cohttp.lwt-core,ppx_deriving,ppx_fields_conv,ppx_sexp_conv,ezjsonm -g -bin-annot -thread -g -I . -c opium_hmap.mli
    # - build opium_kernel opium_misc.o
    # + ocamlfind ocamlc.opt -package hmap,cohttp.lwt-core,ppx_deriving,ppx_fields_conv,ppx_sexp_conv,ezjsonm -g -bin-annot -thread -g -I . -c opium_misc.ml
    # *** omake: 43/106 targets are up to date
    # *** omake: failed (0.17 sec, 14/14 scans, 2/2 rules, 20/54 digests)
    ### stderr ###
    # *** omake: targets were not rebuilt because of errors:
    # [...]
    #    opium_kernel/opium_misc.cmi
    #       depends on: opium_kernel/opium_misc.ml
    #    opium_kernel/opium_misc.cmo
    #       depends on: opium_kernel/opium_misc.ml
    #    opium_kernel/opium_misc.cmx
    #       depends on: opium_kernel/opium_misc.ml
    #    opium_kernel/opium_misc.o
    #       depends on: opium_kernel/opium_misc.ml
    # make: *** [install] Error 2

**Comment by bladewang** [comment]
eventually, I got a version of opium installed on my system, after following commands:

     opam switch 4.02.3
     opam install opium.0.13.3

**Comment by rgrinberg** [comment]
Huh? So 0.15.0 didn't work for you on 4.03? Could you try it on 4.04 as well please.

**Comment by rgrinberg** [comment]
Try pinning the dev-repo. If that works then I will make a point release:

```
$ opam pin add opium --dev-repo
```

**Comment by bladewang** [comment]
Yes，It worked!  thx ~~
