### ISSUE TITLE
Can't install opium on arm =(

### ISSUE THREAD

**Issue by NightBlues** [rgrinberg/opium#70]
Hello, I'm trying to run my litle website writen with opium on my orange pi (clone of raspberry pi), everything works well on my x86 laptop, but I can't install opium through opam on arm (orange pi):
```
$ opam install opium
Your request can't be satisfied:
  - No package matches opium.

No solution found, exiting
$ opam search opium
# Existing packages for 4.03.0:
opium  --  Sinatra like web toolkit based on Lwt + Cohttp
```
I've already successfully installed lwt, cohttp, conf-libev, camlp4. Could you please help me - what is the reason and where should I look to investigate the problem?

**Comment by rgrinberg** [comment]
I'm not sure this has something to do with opium. It must be some other dependency. Try building opium from master. `$ opam pin add opium --dev-repo`

**Comment by NightBlues** [comment]
I've found that I was using old opam version 1.2.0 from debian repos. After upgrading to 1.2.2 I could install opium without any troubles. Thank you and sorry to bother you.
