### ISSUE TITLE
Alternative mimetype lookup

### ISSUE THREAD

**Issue by malthe** [rgrinberg/opium#73]
I need to return `application/javascript; charset=utf-8` instead of the default for `*.js` files.

(Since my source files include non-ascii characters.)

Should `Static_serve.m` take an optional mimetypes module that allows a custom lookup?

**Comment by rgrinberg** [comment]
Sure, I think that would be useful. Why a module though? A function or some sort of map like structure isn't enough?

**Comment by malthe** [comment]
A function would be good!

**Comment by tmattio** [comment]
Fixed in #244
