### ISSUE TITLE
Logging doesn't work

### ISSUE THREAD

**Issue by loxs** [rgrinberg/opium#81]
My toy website is something like this:

```ocaml
let index = get "/" (fun _ -> `Html index_html |> respond')

let _ = App.empty |> App.port 3333 |> index |> App.run_command
```

I run it like this:
```
$ dune exec -- bin/lkl_web_server.exe --help
$ dune exec -- bin/lkl_web_server.exe -v
```

The first command works and displays me the Opium help.
The second one works in the sense that it launches the webserver and it serves the web page.
But the `-v` option doesn't seem to have any effect. It doesn't log anything to the console I'm calling it from, or to any file as it seems.

**Comment by anuragsoni** [comment]
I just started to take a look at the Logs module today. I think you need to setup a reporter from your application, as mentioned in the **Reporter Setup** section of the manual. http://erratique.ch/software/logs/doc/Logs.html

An example can be seen here: https://github.com/mirage/ocaml-cohttp/blob/master/cohttp-lwt-unix/src/debug.ml#L47

**Comment by anuragsoni** [comment]
@loxs I'm closing this as #90 adds an example for how to setup logging with a reporter. Feel free to re-open if you have more issues.

**Comment by loxs** [comment]
Thank you!
