### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by XVilka** [rgrinberg/opium#86]
Because of the Lwt update, basically current release fails to compile.

**Comment by Schniz** [comment]
I guess you're talking about `Error: Unbound module Lwt_log`?

**Comment by anuragsoni** [comment]
Not sure if you've noticed, but https://opam.ocaml.org/packages/opium/opium.0.17.0/ was released sometime ago.

**Comment by rgrinberg** [comment]
@anuragsoni would you like to make a new release?

**Comment by anuragsoni** [comment]
@rgrinberg Sure. I'll prepare one later today.

**Comment by anuragsoni** [comment]
Closing as a new release has been published to opam now. https://opam.ocaml.org/packages/opium/opium.0.17.1/
